basePath: /api/v1
definitions:
  entry.ProjectInfo:
    properties:
      created_at:
        example: "2021-01-01 00:00:00"
        type: string
      desc:
        example: 项目描述
        type: string
      id:
        example: "1"
        type: string
      name:
        example: 项目名称
        type: string
      status:
        example: 1
        type: integer
      updated_at:
        example: "2021-01-01 00:00:00"
        type: string
    type: object
  entry.PromptInfo:
    properties:
      created_at:
        type: string
      id:
        example: "0"
        type: string
      project_id:
        example: "0"
        type: string
      prompt:
        type: string
      status:
        type: integer
      updated_at:
        type: string
    type: object
  entry.ReleaseOrderInfo:
    description: 发布单信息
    properties:
      created_at:
        example: "2021-01-01 00:00:00"
        type: string
      desc:
        example: 发布单描述
        type: string
      id:
        example: 1
        type: integer
      name:
        example: 发布单名称
        type: string
      project_info:
        $ref: '#/definitions/entry.ProjectInfo'
      status:
        example: 1
        type: integer
      updated_at:
        example: "2021-01-01 00:00:00"
        type: string
    type: object
  entry.TaskInfo:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      project_id:
        type: integer
      topic:
        type: string
      updated_at:
        type: string
    type: object
  ginplus.Response:
    description: 通用响应结构
    properties:
      code:
        example: 1
        type: integer
      data: {}
      msg:
        example: success
        type: string
    type: object
  novel.NovelChapterCreateRequestPayload:
    description: 创建章节请求结构体
    properties:
      content:
        description: |-
          @Description 章节内容
          @example "这是章节的内容..."
        type: string
      novel_id:
        description: |-
          @Description 小说ID
          @example 1
        type: integer
      title:
        description: |-
          @Description 章节标题
          @example "第一章 开始"
        type: string
    type: object
  novel.NovelCreateRequestPayload:
    properties:
      author:
        example: ""
        type: string
      category:
        example: ""
        type: string
      cover_image_url:
        example: ""
        type: string
      description:
        example: ""
        type: string
      tags:
        example:
        - ""
        items:
          type: string
        type: array
      title:
        example: ""
        type: string
    required:
    - author
    - title
    type: object
  novel.NovelCreateResponsePayload:
    description: 创建小说响应结构体
    properties:
      id:
        description: |-
          @Description 小说ID
          @example 1
        example: ""
        type: string
    type: object
  novelparser.NovelParserRequestPayload:
    properties:
      novel_content:
        example: ""
        type: string
      system_prompt:
        example: ""
        type: string
    required:
    - novel_content
    - system_prompt
    type: object
  project.ProjectRequestPostPayload:
    properties:
      desc:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  project.ProjectResponsePostPayload:
    properties:
      id:
        example: "0"
        type: string
    type: object
  prompt.PromptRequestPostPayload:
    properties:
      project_id:
        type: integer
      system:
        type: string
    required:
    - project_id
    - system
    type: object
  prompt.PromptRequestPutPayload:
    properties:
      status:
        default: 0
        type: integer
      system:
        type: string
    required:
    - system
    type: object
  prompt.PromptResponsePostPayload:
    properties:
      id:
        example: "0"
        type: string
    type: object
  prompt.PromptResponsePutPayload:
    properties:
      id:
        example: "0"
        type: string
      prompt:
        type: string
    type: object
  releaseorder.ReleaseOrderRequestPostPayload:
    properties:
      desc:
        type: string
      name:
        type: string
      project_id:
        type: integer
    required:
    - name
    - project_id
    type: object
  releaseorder.ReleaseOrderResponsePostPayload:
    properties:
      order_id:
        type: integer
    type: object
  task.TaskExecuteRequestPayload:
    description: 任务执行请求结构体
    type: object
  task.TaskRequestPostPayload:
    description: 任务请求结构体
    properties:
      project_id:
        description: |-
          @Description 项目ID
          @in body
          @required
        example: "123"
        type: string
      topic:
        description: |-
          @Description 任务标题
          @in body
          @required
        example: 完成项目文档
        type: string
    type: object
  task.TaskRequestPutPayload:
    properties:
      project_id:
        type: integer
      topic:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Craft Studio 服务 API 文档
  title: Craft Studio API
  version: "1.0"
paths:
  /novels/chapters/create:
    post:
      consumes:
      - application/json
      description: 创建章节
      parameters:
      - description: 创建章节请求
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/novel.NovelChapterCreateRequestPayload'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/ginplus.Response'
      summary: 创建章节
      tags:
      - 小说
  /novels/create:
    post:
      consumes:
      - application/json
      description: 创建小说
      parameters:
      - description: 创建小说请求
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/novel.NovelCreateRequestPayload'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/ginplus.Response'
            - properties:
                data:
                  $ref: '#/definitions/novel.NovelCreateResponsePayload'
              type: object
      summary: 创建小说
      tags:
      - 小说
  /novels/list:
    get:
      description: 小说列表
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 10
        description: 每页数量
        in: query
        name: page_size
        type: integer
      - description: 小说标题
        in: query
        name: title
        type: string
      - description: 作者
        in: query
        name: author
        type: string
      - description: 分类
        in: query
        name: category
        type: string
      - description: 标签
        in: query
        name: tags
        type: string
      - description: 状态
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/ginplus.Response'
      summary: 小说列表
      tags:
      - 小说
  /novels/parser:
    post:
      consumes:
      - application/json
      description: 小说拆解
      parameters:
      - description: 小说拆解请求
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/novelparser.NovelParserRequestPayload'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/ginplus.Response'
      summary: 小说拆解
      tags:
      - 小说拆解
  /project:
    post:
      consumes:
      - application/json
      description: 创建项目
      parameters:
      - description: 项目信息
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/project.ProjectRequestPostPayload'
      produces:
      - application/json
      responses:
        "200":
          description: 项目信息
          schema:
            $ref: '#/definitions/project.ProjectResponsePostPayload'
      summary: 创建项目
      tags:
      - 项目管理
  /projects:
    get:
      description: 获取项目列表，支持分页和搜索
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 10
        description: 每页数量
        in: query
        name: page_size
        type: integer
      - description: 搜索关键词
        in: query
        name: query
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 项目列表
          schema:
            allOf:
            - $ref: '#/definitions/ginplus.Response'
            - properties:
                data:
                  properties:
                    list:
                      items:
                        $ref: '#/definitions/entry.ProjectInfo'
                      type: array
                    total:
                      type: integer
                  type: object
              type: object
      summary: 获取项目列表
      tags:
      - 项目管理
  /prompt:
    post:
      consumes:
      - application/json
      description: 创建提示词
      parameters:
      - description: 提示词信息
        in: body
        name: prompt
        required: true
        schema:
          $ref: '#/definitions/prompt.PromptRequestPostPayload'
      produces:
      - application/json
      responses:
        "200":
          description: 提示词信息
          schema:
            $ref: '#/definitions/prompt.PromptResponsePostPayload'
      summary: 创建提示词
      tags:
      - 提示词管理
  /prompt/{id}:
    put:
      consumes:
      - application/json
      description: 更新提示词
      parameters:
      - description: 提示词ID
        in: path
        name: id
        required: true
        type: integer
      - description: 提示词信息
        in: body
        name: prompt
        required: true
        schema:
          $ref: '#/definitions/prompt.PromptRequestPutPayload'
      produces:
      - application/json
      responses:
        "200":
          description: 提示词信息
          schema:
            allOf:
            - $ref: '#/definitions/ginplus.Response'
            - properties:
                data:
                  $ref: '#/definitions/prompt.PromptResponsePutPayload'
              type: object
      summary: 更新提示词
      tags:
      - 提示词管理
  /prompts:
    get:
      description: 获取提示词列表
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        required: true
        type: integer
      - default: 10
        description: 每页条数
        in: query
        name: size
        required: true
        type: integer
      - description: 查询条件
        in: query
        name: query
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 提示词列表
          schema:
            allOf:
            - $ref: '#/definitions/ginplus.Response'
            - properties:
                data:
                  properties:
                    list:
                      items:
                        $ref: '#/definitions/entry.PromptInfo'
                      type: array
                    total:
                      type: integer
                  type: object
              type: object
      summary: 获取提示词列表
      tags:
      - 提示词管理
  /release/order:
    post:
      consumes:
      - application/json
      description: 创建发布单
      parameters:
      - description: 发布单请求参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/releaseorder.ReleaseOrderRequestPostPayload'
      produces:
      - application/json
      responses:
        "200":
          description: 发布单响应参数
          schema:
            $ref: '#/definitions/releaseorder.ReleaseOrderResponsePostPayload'
      summary: 创建发布单
      tags:
      - 发布单管理
  /release/orders:
    get:
      description: 获取发布单列表
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 10
        description: 每页条数
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 发布单列表
          schema:
            allOf:
            - $ref: '#/definitions/ginplus.Response'
            - properties:
                data:
                  properties:
                    list:
                      items:
                        $ref: '#/definitions/entry.ReleaseOrderInfo'
                      type: array
                    total:
                      type: integer
                  type: object
              type: object
      summary: 获取发布单列表
      tags:
      - 发布单管理
  /release/orders/{id}:
    get:
      description: 获取发布单
      parameters:
      - description: 发布单ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 发布单信息
          schema:
            allOf:
            - $ref: '#/definitions/ginplus.Response'
            - properties:
                data:
                  $ref: '#/definitions/entry.ReleaseOrderInfo'
              type: object
      summary: 获取发布单
      tags:
      - 发布单管理
  /task:
    post:
      consumes:
      - application/json
      description: 创建任务
      parameters:
      - description: 任务请求
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/task.TaskRequestPostPayload'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/ginplus.Response'
            - properties:
                data:
                  $ref: '#/definitions/task.TaskRequestPostPayload'
              type: object
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/ginplus.Response'
      summary: 创建任务
      tags:
      - 任务管理
  /task/{task_id}:
    put:
      consumes:
      - application/json
      description: 更新任务
      parameters:
      - description: 任务ID
        in: path
        name: task_id
        required: true
        type: integer
      - description: 任务信息
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/task.TaskRequestPutPayload'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/ginplus.Response'
      summary: 更新任务
      tags:
      - 任务管理
  /task/{task_id}/execute:
    post:
      consumes:
      - application/json
      description: 执行任务
      parameters:
      - description: 任务ID
        in: path
        name: task_id
        required: true
        type: integer
      - description: 任务执行请求参数
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/task.TaskExecuteRequestPayload'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/ginplus.Response'
      summary: 执行任务
      tags:
      - 任务管理
  /tasks:
    get:
      description: 获取任务列表
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 10
        description: 每页数量
        in: query
        name: size
        type: integer
      - description: 项目ID
        in: query
        name: project_id
        type: integer
      - description: 搜索关键词
        in: query
        name: query
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            allOf:
            - $ref: '#/definitions/ginplus.Response'
            - properties:
                data:
                  properties:
                    list:
                      items:
                        $ref: '#/definitions/entry.TaskInfo'
                      type: array
                    total:
                      type: integer
                  type: object
              type: object
      summary: 获取任务列表
      tags:
      - 任务管理
swagger: "2.0"
